baseURL: https://discuss.thiswith.me
defaultContentLanguage: en
disqusShortname: discuss-thiswith-me
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
# permalinks:
#   posts: /:section/:year/:month/:title/
pygmentsCodeFences: true
pygmentsUseClasses: true
summaryLength: 50
theme: anatole
taxonomies:
  tag: tags
title: Discuss This With Me
